[project]
name = "masterthesis-llm-optimization-orca"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.0.15",
    "git-python>=1.0.3",
    "pandas>=2.3.0",
    "sentence-transformers>=5.0.0",
    "stix2>=3.0.1",
]
