[project]
name = "artifact"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.0.15",
    "ollama>=0.5.3",
    "pandas>=2.3.0",
]
