name: Generate Repo visualization
on:
  # Run automatically on pushes to the 'main' or 'master' branch
  push:
    branches:
      - "main"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  visualize:
    name: Run Repo Visualizer
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository's code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Run the repo-visualizer action
      - name: Generate visualization
        uses: githubocto/repo-visualizer@0.9.1
        with:
          # Define the name for the output SVG file
          output_file: "images/repo-visualization.svg"
